import React, { useEffect } from 'react';
import { DateTime } from "luxon";

const ContainerBloc = ({ dt, tasks }) => {
  const diffDay = (end, start) => {
    let diffInMonths = end.diff(start, 'months');
    let diffDay = diffInMonths.as('days');
    return Math.ceil(diffDay)
  }
 const addSpan = () => {
   const begin = document.querySelectorAll('.ganttMachine-container-bloc--day--touch--start');
   for (let i = 0 ; i<begin.length ; i++ ) {
   const newSpan = document.createElement('span');
   newSpan.classList.add('progress');
   begin[i].append(newSpan);
  }
 }
  useEffect(() => {
    addSpan();
  }, []);
  return (
  <div className="ganttMachine-container-all">
    {tasks.map((task) =>
    <div className="ganttMachine-container-bloc">
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:11}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:11}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:11}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:11}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:10}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:10}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:10}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:10}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:9}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:9}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:9}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:9}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:8}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:8}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:8}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:8}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:7}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:7}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:7}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:7}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:6}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:6}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:6}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:6}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:5}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:5}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:5}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:5}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:4}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:4}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:4}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:4}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:3}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:3}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:3}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:3}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:2}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:2}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:2}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:2}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:1}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.minus({days:1}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.minus({days:1}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.minus({days:1}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:1}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:1}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:1}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:1}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:2}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:2}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:2}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:2}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:3}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:3}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:3}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:3}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:4}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:4}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:4}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:4}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:5}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:5}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:5}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:5}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:6}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:6}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:6}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:6}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:7}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:7}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:7}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:7}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:8}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:8}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:8}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:8}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:9}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:9}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:9}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:9}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:10}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:10}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:10}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" })>dt.plus({days:10}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:11}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:11}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:11}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:11}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:12}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:12}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:12}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:12}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:13}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:13}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:13}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:13}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()===dt.plus({days:14}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()===dt.plus({days:14}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:14}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" })>dt.plus({days:14}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:15}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:15}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:15}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:15}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:16}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:16}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:16}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:16}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:17}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:17}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:17}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:17}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:18}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:18}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:18}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:18}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
      <div className="ganttMachine-container-bloc--day">
        <span className={(DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:19}).toMillis()) ? "ganttMachine-container-bloc--day--touch--start" : (DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()==dt.plus({days:19}).toMillis()) ? "ganttMachine-container-bloc--day--touch--end" : (DateTime.fromISO(`${task.start.substring(0,4)}-${task.start.substring(5,7)}-${task.start.substring(8,10)}`, { locale: "fr" }).toMillis()<dt.plus({days:19}).toMillis() && DateTime.fromISO(`${task.end.substring(0,4)}-${task.end.substring(5,7)}-${task.end.substring(8,10)}`, { locale: "fr" }).toMillis()>dt.plus({days:19}).toMillis()) ? "ganttMachine-container-bloc--day--touch" : "ganttMachine-container-bloc--empty" }></span>
      </div>
    </div>
    )}
  </div>
    );
};

export default ContainerBloc;
